# Generated by Django 5.1.7 on 2025-05-13 16:24

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='age_18_plus',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+375 (29) XXX-XX-XX'", regex='^\\+375\\d{9}$')], verbose_name='Номер телефона'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('birth_date__lte', datetime.date(2007, 5, 18))), name='age_18_plus'),
        ),
    ]
