# Generated by Django 5.1.7 on 2025-05-23 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0007_remove_user_age_18_plus_user_age_18_plus'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='age_18_plus',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('birth_date__lte', datetime.date(2007, 5, 28))), name='age_18_plus'),
        ),
    ]
