# Generated by Django 5.1.7 on 2025-05-12 18:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название страны')),
                ('winter_climate', models.CharField(max_length=100, verbose_name='Зимний климат')),
                ('summer_climate', models.CharField(max_length=100, verbose_name='Летний климат')),
                ('description', models.TextField(blank=True, verbose_name='Описание страны')),
                ('image', models.ImageField(blank=True, null=True, upload_to='countries/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название отеля')),
                ('stars', models.PositiveSmallIntegerField(choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')], verbose_name='Звездность')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за день')),
                ('description', models.TextField(blank=True, verbose_name='Описание отеля')),
                ('amenities', models.TextField(blank=True, verbose_name='Удобства')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotels/', verbose_name='Изображение')),
                ('available_rooms', models.PositiveIntegerField(default=0, verbose_name='Доступные номера')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_weeks', models.PositiveSmallIntegerField(choices=[(1, '1 неделя'), (2, '2 недели'), (3, '3 недели'), (4, '4 недели')], verbose_name='Длительность (недели)')),
                ('departure_date', models.DateField(verbose_name='Дата отправления')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Дата возвращения')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Общая цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный тур')),
                ('max_participants', models.PositiveIntegerField(default=20, verbose_name='Макс. участников')),
                ('current_participants', models.PositiveIntegerField(default=0, verbose_name='Текущие участники')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Турпакет',
                'verbose_name_plural': 'Турпакеты',
                'ordering': ['departure_date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждено'), ('paid', 'Оплачено'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='pending', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('participants', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество участников')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tourpackage', verbose_name='Турпакет')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tourpackage', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
                'unique_together': {('user', 'tour')},
            },
        ),
    ]
