# Generated by Django 5.1.7 on 2025-05-15 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=100, verbose_name='Название агентства')),
                ('legal_name', models.CharField(max_length=100, verbose_name='Юридическое название')),
                ('tax_id', models.CharField(max_length=20, unique=True, verbose_name='ИНН')),
                ('registration_number', models.CharField(max_length=50, verbose_name='ОГРН')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Банк')),
                ('bank_account_number', models.CharField(max_length=50, verbose_name='Расчетный счет')),
                ('correspondent_account', models.CharField(max_length=50, verbose_name='Корреспондентский счет')),
                ('bic', models.CharField(max_length=20, verbose_name='БИК')),
                ('director_name', models.CharField(max_length=100, verbose_name='Директор')),
                ('license_number', models.CharField(max_length=50, verbose_name='Номер лицензии')),
                ('license_issued_by', models.CharField(max_length=100, verbose_name='Кем выдана лицензия')),
                ('license_issue_date', models.DateField(verbose_name='Дата выдачи лицензии')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='agency/logos/', verbose_name='Логотип')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Реквизиты агентства',
                'verbose_name_plural': 'Реквизиты агентства',
                'db_table': 'agency_details',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок новости')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-адрес')),
                ('summary', models.CharField(max_length=250, verbose_name='Краткое содержание')),
                ('content', models.TextField(verbose_name='Полное содержание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/images/%Y/%m/%d/', verbose_name='Изображение')),
                ('category', models.CharField(choices=[('promo', 'Акции и скидки'), ('country', 'Новости стран'), ('visa', 'Визовые новости'), ('airlines', 'Авиакомпании'), ('events', 'События')], default='country', max_length=20, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_news_created_0f8435_idx'), models.Index(fields=['category'], name='core_news_categor_d0a088_idx')],
            },
        ),
    ]
