# Generated by Django 5.1.7 on 2025-05-15 18:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_agencydetails_news'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('department', models.CharField(choices=[('management', 'Руководство'), ('sales', 'Продажи'), ('booking', 'Бронирование'), ('marketing', 'Маркетинг'), ('support', 'Поддержка')], default='sales', max_length=20, verbose_name='Отдел')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/%Y/%m/%d/', verbose_name='Фото')),
                ('bio', models.TextField(verbose_name='О сотруднике')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('is_contact', models.BooleanField(default=True, verbose_name='Показывать контакты')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='Введите термин или вопрос', max_length=200, verbose_name='Термин/Вопрос')),
                ('slug', models.SlugField(help_text='Уникальная часть URL для этого термина', max_length=200, unique=True, verbose_name='URL-адрес термина')),
                ('definition', models.TextField(help_text='Полное объяснение термина или ответ на вопрос', verbose_name='Определение/Ответ')),
                ('short_definition', models.CharField(blank=True, help_text='Краткая версия (до 250 символов)', max_length=250, verbose_name='Краткое определение')),
                ('category', models.CharField(choices=[('general', 'Общие термины'), ('documents', 'Документы и визы'), ('transport', 'Транспорт'), ('accommodation', 'Проживание'), ('insurance', 'Страхование'), ('payments', 'Оплата и финансы'), ('safety', 'Безопасность')], default='general', max_length=20, verbose_name='Категория')),
                ('is_faq', models.BooleanField(default=False, help_text='Отметьте, если это частый вопрос', verbose_name='Частый вопрос?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Термин словаря',
                'verbose_name_plural': 'Термины словаря',
                'ordering': ['term'],
                'indexes': [models.Index(fields=['term'], name='core_glossa_term_3eded1_idx'), models.Index(fields=['category'], name='core_glossa_categor_f7f8da_idx'), models.Index(fields=['is_faq'], name='core_glossa_is_faq_412c30_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название вакансии')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-адрес вакансии')),
                ('short_description', models.CharField(max_length=250, verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Полное описание')),
                ('requirements', models.TextField(help_text='Перечислите требования к кандидату', verbose_name='Требования')),
                ('responsibilities', models.TextField(help_text='Перечислите основные обязанности', verbose_name='Обязанности')),
                ('conditions', models.TextField(help_text='Что мы предлагаем', verbose_name='Условия работы')),
                ('salary', models.CharField(blank=True, max_length=100, null=True, verbose_name='Зарплата')),
                ('job_type', models.CharField(choices=[('full_time', 'Полная занятость'), ('part_time', 'Частичная занятость'), ('remote', 'Удаленная работа'), ('internship', 'Стажировка')], default='full_time', max_length=20, verbose_name='Тип занятости')),
                ('department', models.CharField(choices=[('sales', 'Продажи'), ('tour_ops', 'Туроперация'), ('customer_service', 'Клиентский сервис'), ('marketing', 'Маркетинг'), ('hr', 'HR'), ('finance', 'Финансы')], max_length=20, verbose_name='Отдел')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('experience_required', models.CharField(default='Без опыта', max_length=100, verbose_name='Требуемый опыт')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at'], name='core_vacanc_publish_0d92da_idx'), models.Index(fields=['is_published'], name='core_vacanc_is_publ_f8951f_idx'), models.Index(fields=['department'], name='core_vacanc_departm_0d1519_idx')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.PositiveSmallIntegerField(choices=[(5, 'Отлично'), (4, 'Хорошо'), (3, 'Удовлетворительно'), (2, 'Плохо'), (1, 'Ужасно')], default=5, verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_review_created_fff155_idx'), models.Index(fields=['rating'], name='core_review_rating_41e437_idx')],
            },
        ),
    ]
