# Generated by Django 5.1.7 on 2025-05-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee_glossaryterm_vacancy_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Отметьте, если сотрудник работает в компании', verbose_name='Активный сотрудник'),
        ),
    ]
