# Generated by Django 5.1.7 on 2025-05-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_employee_is_active'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='review',
            name='core_review_created_fff155_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='core_review_rating_41e437_idx',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(5, '★★★★★'), (4, '★★★★☆'), (3, '★★★☆☆'), (2, '★★☆☆☆'), (1, '★☆☆☆☆')], default=5, verbose_name='Оценка'),
        ),
    ]
