# Generated by Django 5.1.7 on 2025-05-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_review_core_review_created_fff155_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Промокод')),
                ('description', models.TextField(verbose_name='Описание акции')),
                ('discount_type', models.CharField(choices=[('percentage', 'Процент'), ('fixed', 'Фиксированная сумма')], default='percentage', max_length=10, verbose_name='Тип скидки')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Размер скидки')),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Минимальная сумма заказа')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала действия')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания действия')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальное количество использований')),
                ('current_uses', models.PositiveIntegerField(default=0, verbose_name='Текущее количество использований')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('archived', 'В архиве'), ('expired', 'Истекший')], default='active', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promo_codes/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['code'], name='core_promoc_code_957ef8_idx'), models.Index(fields=['status'], name='core_promoc_status_1227b5_idx'), models.Index(fields=['end_date'], name='core_promoc_end_dat_dde281_idx')],
            },
        ),
    ]
