# Generated by Django 5.1.7 on 2025-05-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.CharField(blank=True, max_length=100, verbose_name='Столица'),
        ),
        migrations.AddField(
            model_name='country',
            name='weather_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Данные о погоде'),
        ),
        migrations.AddField(
            model_name='country',
            name='weather_last_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновление погоды'),
        ),
    ]
