# Generated by Django 5.1.7 on 2025-05-16 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_country_capital_country_weather_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='capital',
        ),
    ]
