# Generated by Django 5.1.7 on 2025-05-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_country_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Столица'),
        ),
    ]
