# Generated by Django 5.1.7 on 2025-05-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_review_hotel'),
    ]

    operations = [
    ]
